#!/bin/sh

echo "Please talk to me ..."
while true #depois vem uma mensagem de pedido, em seguida vem uma loop “infinito” com o While true
do
  read INPUT_STRING
  case $INPUT_STRING in
	hello)
		echo "Hello yourself!"
		;;
	bye)
		echo "See you again!"
		break
		;;
	*)
		echo "Sorry, I don't understand"
		;;
  	   esac
done
echo 
echo "That's all folks!"
